services:
  # Сервис базы данных
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: solta
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  # Твой Flask API
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Важно: обращаемся к базе по имени сервиса 'db', а не по localhost!
      DATABASE_URL: "postgresql://solta:mysecretpassword@db:5432/orders_db"
    depends_on:
      - db
    networks:
      - backend_net

# Создаем изолированную сеть
networks:
  backend_net:
    driver: bridge

# Создаем Volume, который Docker сохранит на диске D (в папке WSL)
volumes:
  postgres_data:
