curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://google.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://facebook.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://twitter.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://linkedin.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://github.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://stackoverflow.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://amazon.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://apple.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://microsoft.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://netflix.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://reddit.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://youtube.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://instagram.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://pinterest.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://quora.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://tumblr.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://spotify.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://airbnb.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://uber.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://lyft.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://dropbox.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://slack.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://trello.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://asana.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://notion.so
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://github.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://gitlab.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://bitbucket.org
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://codepen.io
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://jsfiddle.net
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://codewars.com
curl -w "Time Total: %{time_total}s\n" -o /dev/null -s https://leetcode.com